# Generated by Django 5.0.3 on 2024-05-03 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeModel',
            fields=[
                ('Id_account_type', models.AutoField(primary_key=True, serialize=False, verbose_name='Id account type')),
                ('Code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{1}-[0-9]{2}$')], verbose_name='Code')),
                ('Description', models.CharField(max_length=100, verbose_name='Description')),
                ('Subaccount', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')], verbose_name='Subaccount')),
                ('Percent', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percent')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('Id_customer', models.AutoField(primary_key=True, serialize=False, verbose_name='Id customer')),
                ('First_name', models.CharField(max_length=100, verbose_name='First name')),
                ('Last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('Address', models.CharField(max_length=100, verbose_name='Address')),
                ('Postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2}-[0-9]{3}$')], verbose_name='Postal code')),
                ('City', models.CharField(max_length=100, verbose_name='City')),
                ('Pesel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')], verbose_name='PESEL')),
                ('Birth_date', models.DateField(verbose_name='Birth day')),
                ('Birth_city', models.CharField(max_length=100, verbose_name='Birth city')),
                ('Identification', models.CharField(max_length=9, verbose_name='Identification')),
                ('Created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('Created_employee', models.CharField(max_length=50, verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterModel',
            fields=[
                ('Id_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('Country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{2}$')])),
                ('Bank_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('Id_account', models.AutoField(primary_key=True, serialize=False, verbose_name='Id account')),
                ('Number_IBAN', models.CharField(blank=True, max_length=28, verbose_name='IBAN number')),
                ('Balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance')),
                ('Debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debit')),
                ('Free_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Free balance')),
                ('Percent', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percent')),
                ('Created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('Created_employee', models.CharField(max_length=50, verbose_name='Employee')),
                ('FK_Id_account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apibankapp.accounttypemodel')),
                ('FK_Id_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apibankapp.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OperationModel',
            fields=[
                ('Id_operation', models.AutoField(primary_key=True, serialize=False, verbose_name='Id operation')),
                ('Type_operation', models.IntegerField(choices=[('', '--------'), (1, 'Deposit'), (2, 'Withdrawal')], verbose_name='Type operation')),
                ('Value_operation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Value operation')),
                ('Balance_after_operation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance after operation')),
                ('Operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Operation date')),
                ('Operation_employee', models.CharField(max_length=50, verbose_name='Employee')),
                ('FK_Id_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apibankapp.accountmodel')),
            ],
        ),
    ]
