# Generated by Django 5.0.3 on 2024-05-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0004_alter_accountmodel_fk_id_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='FK_Id_account_type',
            new_name='Account_type',
        ),
    ]
