# Generated by Django 5.0.3 on 2024-05-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0005_rename_fk_id_account_type_accountmodel_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='FK_Id_customer',
            new_name='Customer',
        ),
    ]
