# Generated by Django 5.0.3 on 2024-05-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0007_alter_accountmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Account', to='apibankapp.customermodel'),
        ),
    ]
