# Generated by Django 5.0.3 on 2024-05-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0008_alter_accountmodel_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationmodel',
            old_name='FK_Id_account',
            new_name='Id_account',
        ),
    ]
