# Generated by Django 5.0.3 on 2024-05-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0011_rename_address_customermodel_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='Created_employee',
            new_name='created_employee',
        ),
    ]
