# Generated by Django 5.0.3 on 2024-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0013_rename_account_type_accountmodel_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttypemodel',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='accounttypemodel',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='accounttypemodel',
            old_name='Id_account_type',
            new_name='id_account_type',
        ),
        migrations.RenameField(
            model_name='accounttypemodel',
            old_name='Percent',
            new_name='percent',
        ),
        migrations.RenameField(
            model_name='accounttypemodel',
            old_name='Subaccount',
            new_name='subaccount',
        ),
    ]
