# Generated by Django 5.0.3 on 2024-05-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0014_rename_code_accounttypemodel_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametermodel',
            old_name='Bank_number',
            new_name='bank_number',
        ),
        migrations.RenameField(
            model_name='parametermodel',
            old_name='Country_code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='parametermodel',
            old_name='Id_parameter',
            new_name='id_parameter',
        ),
    ]
