# Generated by Django 5.0.3 on 2024-05-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0015_rename_bank_number_parametermodel_bank_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Balance_after_operation',
            new_name='balance_after_operation',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Id_account',
            new_name='id_account',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Id_operation',
            new_name='id_operation',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Operation_date',
            new_name='operation_date',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Operation_employee',
            new_name='operation_employee',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Type_operation',
            new_name='type_operation',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='Value_operation',
            new_name='value_operation',
        ),
    ]
