# Generated by Django 5.0.3 on 2024-05-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0016_rename_balance_after_operation_operationmodel_balance_after_operation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='number_IBAN',
            new_name='number_iban',
        ),
    ]
