# Generated by Django 5.0.3 on 2024-05-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0017_rename_number_iban_accountmodel_number_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='id_customer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
