# Generated by Django 5.0.3 on 2024-05-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0018_alter_customermodel_id_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
