# Generated by Django 5.0.3 on 2024-05-16 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0019_alter_customermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='pesel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2}-[0-9]{3}$')]),
        ),
    ]
