# Generated by Django 5.0.3 on 2024-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0020_alter_customermodel_city_alter_customermodel_pesel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='birth_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='identification',
            field=models.CharField(max_length=9),
        ),
    ]
