# Generated by Django 5.0.3 on 2024-05-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0021_alter_customermodel_birth_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='created_employee',
            field=models.CharField(max_length=50),
        ),
    ]
