# Generated by Django 5.0.3 on 2024-05-16 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0022_alter_customermodel_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='free_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='id_account',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='number_iban',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
