# Generated by Django 5.0.3 on 2024-05-16 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0024_alter_accountmodel_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypemodel',
            name='code',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{1}-[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='id_account_type',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='subaccount',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')]),
        ),
    ]
