# Generated by Django 5.0.3 on 2024-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0025_alter_accounttypemodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='balance_after_operation',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='id_operation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='operation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='operation_employee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='type_operation',
            field=models.IntegerField(choices=[('', '--------'), (1, 'Deposit'), (2, 'Withdrawal')]),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='value_operation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
