# Generated by Django 5.0.3 on 2024-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0029_alter_accountmodel_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='type_operation',
            field=models.IntegerField(choices=[('', '--------'), (1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest')]),
        ),
    ]
