# Generated by Django 5.0.3 on 2024-08-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0030_alter_operationmodel_type_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='address',
            new_name='street',
        ),
    ]
