# Generated by Django 5.0.3 on 2024-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0032_customermodel_apartment_customermodel_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('date_log', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.CharField(max_length=50)),
                ('function_log', models.CharField(max_length=50)),
                ('duration_log', models.DecimalField(decimal_places=6, max_digits=12)),
                ('data_log', models.CharField(blank=True, max_length=250)),
                ('user_log', models.CharField(max_length=50)),
                ('status_log', models.CharField(max_length=20)),
            ],
        ),
    ]
