# Generated by Django 5.0.3 on 2024-11-17 15:33

import apibankapp.models
import apibankapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibankapp', '0038_alter_accountmodel_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apibankapp.models.CustomerModel.get_upload_path, validators=[apibankapp.validators.validator_file_size]),
        ),
    ]
